'use strict';
var FS = require('fs');
var Inherits = require('util').inherits;
var Converter = require('api-spec-converter');
var Types = Converter.Types;
var XMLParser = require('xml2js').parseString;

var Kaltura = module.exports = function() {
  Kaltura.super_.apply(this, arguments);
  this.type = 'kaltura';
  this.converters = {
    swagger_2: function(kaltura, callback) {
      var swagger = {swagger: '2.0'};
      swagger.host = 'www.kaltura.com';
      swagger.schemes = ['http', 'https'];
      swagger.basePath = '/api_v3';
      swagger.info = {title: 'Kaltura', description: 'The Kaltura API', version: '3'};
      swagger.securityDefinitions = {
        "partnerId": {
          in: "query",
          name: 'partnerId',
          type: 'apiKey',
          description: "Your Partner ID",
        },
        "secret": {
          in: 'query',
          name: 'secret',
          type: 'apiKey',
          description: 'Your API secret'
        },
        "session": {
          in: 'query',
          name: 'ks',
          type: 'apiKey',
          description: 'A session ID generated by calling /service/session/action/start',
        }
      }
      var services = kaltura.spec.services[0].service;
      var enums = kaltura.spec.enums[0].enum;
      enums = convertEnums(enums);
      var classes = kaltura.spec.classes[0].class;
      swagger.definitions = convertClasses(classes, enums);
      swagger.paths = convertServices(services, enums, swagger.definitions);
      swagger.tags = [];
      services.forEach(function(s) {swagger.tags.push({
        name: s.$.name,
        description: s.$.description,
      })})
      callback(null, swagger);
    }
  }
};
Types['kaltura'] = Kaltura;
Inherits(Kaltura, Converter.BaseType);

Kaltura.prototype.formatName = 'kaltura';
Kaltura.prototype.supportedVersions = ['1.0'];
Kaltura.prototype.getFormatVersion = function () {
  return '1.0';
}

Kaltura.prototype.parsers = [function(string, cb) {
  XMLParser(string, function(err, parsed) {
    cb(err, parsed ? parsed.xml : null);
  })
}];

Kaltura.prototype.checkFormat = function (spec) {
  return true;
}

var convertEnums = function(enums) {
  var ret = {};
  enums.forEach(function(enm) {
    ret[enm.$.name] = (enm.const || []).map(function(c) {
      return {name: c.$.name, value: c.$.value}
    })
  })
  return ret;
}

var convertClasses = function(classes, enums) {
  var definitions = {KalturaObjectBase: {}};
  classes.forEach(function(cls) {
    var base = cls.$.base;
    var def = definitions[cls.$.name] = {};
    if (base) def.allOf = [{$ref: '#/definitions/' + base}];
    def.description = cls.$.description;
    def.properties = {};
    var props = cls.property || [];
    props.forEach(function(prop) {
      var swaggerProp = def.properties[prop.$.name] = {};
      if (prop.$.type.indexOf('Kaltura') === 0) {
        swaggerProp.$ref = '#/definitions/' + prop.$.type;
        return;
      } else if (prop.$.arrayType && prop.$.arrayType.indexOf('Kaltura') === 0) {
        swaggerProp.type = 'array';
        swaggerProp.items = {$ref: '#/definitions/' + prop.$.arrayType};
        return;
      }
      if (prop.$.readOnly && prop.$.readOnly !== '0') {
        swaggerProp.readOnly = true;
      }
      swaggerProp.description = prop.$.description || undefined;
      if (swaggerProp.description) swaggerProp.description = swaggerProp.description.replace(/\n\s*\t\s*$/g, '').trim()
      swaggerProp.type = convertType(prop.$.type);
      if (prop.$.enumType) {
        var enm = enums[prop.$.enumType];
        swaggerProp.enum = enm.map(function(e) {
          return swaggerProp.type === 'integer' ? parseInt(e.value) : e.value;
        })
      }
    })
  });
  return definitions;
}

var convertServices = function(services, enums, definitions) {
  var paths = {};
  services.forEach(function(service) {
    var actions = service.action;
    actions.forEach(function(action) {
      var path = paths['/service/' + service.$.name + '/action/' + action.$.name] = {};
      path = path.get = {};
      path.description = action.$.description;
      path.tags = [service.$.name];
      path.parameters = [{
        name: 'format',
        enum: [1, 2, 3],
        description: '1 = JSON, 2 = XML, 3 = PHP',
        in: 'query',
        type: 'integer',
        x_df_default: 1,
      }, {
        name: 'ks',
        description: 'Kaltura Session ID',
        in: 'query',
        type: 'string',
      }];
      var parameters = action.param || [];
      parameters.forEach(function(param) {
        if (param.$.type.indexOf('Kaltura') === 0) {
          path.parameters = path.parameters.concat(getExpandedQueryParameters(param, enums, definitions))
          return;
        } else if (param.$.type === "array" || param.$.type === "file") {
          return;
        }
        var newParam = {
          name: param.$.name,
          in: 'query',
          description: param.$.description,
          type: convertType(param.$.type),
          required: param.optional === 1,
        };
        var enumVals = enums[param.$.enumType];
        if (enumVals) {
          if (newParam.description) newParam.description += '\n\n';
          newParam.enum = enumVals.map(function(e) {return e.value})
        }
        path.parameters.push(newParam)
      });
      path.responses = {
        '200': {
          description: 'Success',
        }
      }
      var result = action.result[0];
      if (result) {
        var resultType = result.$.type;
        if (resultType.indexOf('Kaltura') === 0) {
          path.responses['200'].schema = {'$ref': '#/definitions/' + result.$.type}
        }
      }
    });
  });
  return paths;
}

var getExpandedQueryParameters = function(param, enums, definitions) {
  var params = [];
  var schema = definitions[param.$.type];
  if (!schema) throw new Error("Schema " + param.$.type + " not found");
  var addProps = function(props) {
    for (var prop in props) {
      var propDef = props[prop];
      if (propDef.readOnly) continue;
      var newParam = {
        type: propDef.type,
        in: 'query',
        name: param.$.name + '[' + prop + ']',
        enum: propDef.enum,
        description: propDef.description,
      };
      params.push(newParam);
    }
  }
  addProps(schema.properties);
  (schema.allOf || []).forEach(function(base) {
    var baseSchema = definitions[base.$ref.substring('#/definitions/'.length)];
    addProps(baseSchema.properties);
  })
  return params;
}

var convertType = function(type) {
  if (type === "bool") return "boolean";
  if (type === "array") return "array";
  if (type === "int" || type === "bigint") return "integer";
  if (type === "float") return "number";
  if (type === "string") return "string";
  if (type === "map") return "object";
  throw new Error("Unknown type:" + type);
}
