const utils = require('./utils');

const DEBUG_OP = {service: '', action: ''};
const _ = require('lodash');

const DEPRECATED = [
  "document",
  "search",
  "mixing",
  "liveChannel",
  "liveChannelSegment",
]

const BASE_SWAGGER = {
  swagger: '2.0',
  schemes: ['https', 'http'],
};

const TARGET_API = process.env.TARGET_API || 'ovp';

if (TARGET_API === 'ott') {
  Object.assign(BASE_SWAGGER, {
    host: 'tvpapi-us-preprod.ott.kaltura.com',
    basePath: '/api_v3',
    info: {title: "Kaltura OTT", description: "The Kaltura OTT API"},
    produces: ['application/json', 'text/xml'],
  })
} else {
  Object.assign(BASE_SWAGGER, {
    host: 'www.kaltura.com',
    basePath: '/api_v3',
    info: {title: "Kaltura VPaaS", description: "The Kaltura VPaaS API"},
  })
}

const getClassnameFromRef = function(ref) {
  return ref.match(/definitions\/(.*)$/)[1];
}
const getRefFromClassname = function(c) {
  return '#/definitions/' + c;
}

const SwaggerBuilder = module.exports = function() {
  this.swagger = Object.assign({}, BASE_SWAGGER);
  this.swagger.security = [{ks: []}];
  if (TARGET_API === 'ovp') {
    this.swagger.securityDefinitions = {
      "ks": {
        in: 'query',
        name: 'ks',
        type: 'apiKey',
        description: 'A session ID generated by calling /service/session/action/start',
      }
    }
    this.swagger.parameters = {
      ks: {
        name: 'ks',
        in: 'query',
        type: 'string',
        'x-global': true,
      }
    };
    this.swagger.parameters.format = {
      name: 'format',
      enum: [1, 2, 3],
      'x-enumLabels': ['JSON', 'XML', 'PHP'],
      'x-consoleDefault': 1,
      description: 'The format of the response',
      in: 'query',
      type: 'integer',
      'x-global': true,
    }
  } else {
    this.swagger.securityDefinitions = {
      "ks": {
        in: 'body',
        name: 'ks',
        type: 'apiKey',
        description: 'A Kaltura session ID',
      }
    }
  }
}

SwaggerBuilder.prototype.run = function(kaltura) {
  var services = kaltura.services[0].service;
  var enums = kaltura.enums[0].enum;
  var classes = kaltura.classes[0].class;
  this.swagger.info.version = kaltura.$.apiVersion;
  this.addEnums(enums);
  this.addDefinitions(classes);
  this.addPaths(services, kaltura.errors[0].error);
  this.setTags(services);
  this.addErrors(kaltura.errors[0].error);
  this.finish();
  return this.swagger;
}

SwaggerBuilder.prototype.finish = function() {
  this.setInputOptions();
  this.fixDefinitions();
  this.fixFileOperations();
  if (TARGET_API === 'ovp') {
    this.swagger.paths['/service/apptoken/action/startSession'].get.security = [];
  }
}

SwaggerBuilder.prototype.setTags = function(services) {
  this.swagger.tags = services.map(s => {
    let tag = {
      name: s.$.name,
      description: utils.fixMarkdown(s.$.description),
    };
    if (s.$.plugin) tag['x-plugin'] = s.$.plugin;
    return tag;
  })
  .sort(function(t1, t2) {
    return t1.name > t2.name ? 1 : -1;
  })
}

SwaggerBuilder.prototype.addEnums = function(enums) {
  this.swagger['x-enums'] = {};
  enums.forEach(enm => {
    var values = (enm.const || []).map(c => {
      var value = c.$.value;
      if (enm.$.enumType === 'int') value = parseInt(value)
      return {value, name: c.$.name};
    })
    this.swagger['x-enums'][enm.$.name] = {
      title: enm.$.name,
      oneOf: values.map(v => {
        return {
          title: v.name,
          enum: [v.value],
        }
      }),
    }
  })
}

SwaggerBuilder.prototype.addDefinitions = function(classes) {
  this.swagger.definitions = {KalturaObjectBase: {}};
  if (TARGET_API === 'ott') {
    this.swagger.definitions.OTTRequest = {
      type: 'object',
      properties: {
        ks: {type: 'string'},
        version: {
          type: 'string',
          default: this.swagger.info.version,
        },
      }
    }
  }
  classes.forEach((cls) => {
    var base = cls.$.base;
    var def = this.swagger.definitions[cls.$.name] = {};
    if (base) def.allOf = [{$ref: getRefFromClassname(base)}];
    let descriptionParts = [
      utils.extractPropertiesAsMarkdown(cls),
      utils.fixMarkdown(cls.$.description),
    ];
    def.title = cls.$.name;
    def.type = 'object';
    def.description = descriptionParts.filter(p => p).join('\n\n') || undefined;
    def.properties = {};
    var props = cls.property || [];
    props.forEach((prop) => {
      var swaggerProp = def.properties[prop.$.name] = {};
      if (prop.$.type.indexOf('Kaltura') === 0) {
        swaggerProp.$ref = getRefFromClassname(prop.$.type);
        return;
      } else if (prop.$.arrayType && prop.$.arrayType.indexOf('Kaltura') === 0) {
        swaggerProp.type = 'array';
        swaggerProp.items = {$ref: getRefFromClassname(prop.$.arrayType)};
        return;
      }
      if (prop.$.readOnly && prop.$.readOnly !== '0') {
        swaggerProp.readOnly = true;
      }

      let descriptionParts = [
        utils.extractPropertiesAsMarkdown(prop),
      ];
      swaggerProp.type = utils.convertType(prop.$.type);
      if (prop.$.enumType) {
        descriptionParts.push('Enum Type: `' + prop.$.enumType + '`');
        var enm = this.swagger['x-enums'][prop.$.enumType];
        let enumOptions = utils.getUniqueEnumOptions(enm);
        swaggerProp.enum = enumOptions.map((opt) => {
          return swaggerProp.type === 'integer' ? parseInt(opt.enum[0]) : opt.enum[0];
        });
        if (!swaggerProp.enum.length) delete swaggerProp.enum;
        swaggerProp['x-enumType'] = prop.$.enumType;
        if (prop.$.enumType !== 'KalturaLanguage') {
          swaggerProp['x-enumLabels'] = enumOptions.map((opt) => {
            return opt.title;
          })
        }
      }
      descriptionParts.push(utils.fixMarkdown(prop.$.description))
      let desc = descriptionParts.filter(p => p).join('\n\n');
      if (desc) swaggerProp.description = desc;
    })
  });
}

SwaggerBuilder.prototype.createGetOperation = function(service, action, path, expandedParams) {
  const log = false;
  let op = path.get = {};
  op.description = utils.fixMarkdown(action.$.description);
  op.tags = [service.$.name];
  op.operationId = service.$.name + '.' + action.$.name;
  op.parameters = [{
    $ref: '#/parameters/format',
  }]
  if (action.$.sessionRequired === 'none') {
    op.security = [];
  } else {
    op.parameters.unshift({
      $ref: '#/parameters/ks',
    })
  }
  var parameters = action.param || [];
  parameters.forEach((param) => {
    if (param.$.type.indexOf('Kaltura') === 0) {
      var exParams = expandedParams[param.$.type];
      if (!exParams) {
        exParams = expandedParams[param.$.type] = this.getExpandedQueryParameters(param.$.type);
      }
      op['x-parameterGroups'] = op['x-parameterGroups'] || [];
      var group = {
        name: param.$.name,
        description: 'Object Type: `' + param.$.type + '`',
        schema: {$ref: getRefFromClassname(param.$.type)},
        subGroups: [],
      };
      var GROUP_REGEX = /(.*)\[[^\]]+\]$/;
      var getGroup = (name, groups) => {
        var groups = groups || op['x-parameterGroups'];
        var group = groups.filter(g => g.name === name)[0];
        if (group) return group;
        return groups.filter(g => g.subGroups).map(g => getGroup(name, g.subGroups)).filter(g => g)[0];
      }
      addGroup = (name) => {
        if (getGroup(name)) return;
        var parentGroup = name.match(GROUP_REGEX)[1];
        parentGroup = getGroup(parentGroup);
        parentGroup.subGroups = parentGroup.subGroups || [];
        parentGroup.subGroups.push({name: name})
      }
      op['x-parameterGroups'].push(group);
      exParams = exParams.map((p) => {
        p = JSON.parse(JSON.stringify(p));
        p.name = param.$.name + p.name;
        var group = p.name.match(/(.*)\[[^\]]+\]$/)[1];
        p['x-group'] = group;
        addGroup(group)
        if (p['x-showCondition']) p['x-showCondition'].name = param.$.name + p['x-showCondition'].name;
        return p;
      });
      op.parameters = op.parameters.concat(exParams);
      if (log) console.log('exparam', exParams);
      return;
    } else if (param.$.type === "array") {
      return;
    }
    var newParam = {
      name: param.$.name,
      in: 'query',
      description: utils.fixMarkdown(param.$.description),
      type: utils.convertType(param.$.type),
      required: param.$.optional !== "1",
    };
    var enm = this.swagger['x-enums'][param.$.enumType];
    if (enm) {
      var msg = 'Enum Type: `' + param.$.enumType + '`';
      newParam.description = msg + (newParam.description ? '\n\n' + newParam.description : '');
      let enumOptions = utils.getUniqueEnumOptions(enm);
      newParam.enum = enumOptions.map(e => e.enum[0]);
      if (!newParam.enum.length) delete newParam.enum;
      newParam['x-enumLabels'] = enumOptions.map(e => e.title)
      newParam['x-enumType'] = enm.title;
    }
    if (log) console.log('param', newParam);
    op.parameters.push(newParam)
  });
  return op;
}

SwaggerBuilder.prototype.createPostOperation = function(service, action, path) {
  const log = false;
  let op = path.post = {};
  op.description = utils.fixMarkdown(action.$.description);
  op.tags = [service.$.name];
  op.operationId = service.$.name + '.' + action.$.name;
  let bodyParam = {
    name: 'body',
    in: 'body',
    schema: {
      allOf: [{$ref: '#/definitions/OTTRequest'}],
      type: 'object',
      properties: {}
    }
  };
  op.parameters = [bodyParam];
  (action.param || []).forEach(param => {
    let pSchema = bodyParam.schema.properties[param.$.name] = {};
    if (param.$.type.indexOf('Kaltura') === 0) {
      pSchema.$ref = getRefFromClassname(param.$.type);
    } else {
      pSchema.type = utils.convertType(param.$.type);
    }
  });
  return op;
}

SwaggerBuilder.prototype.addPaths = function(services, errors) {
  this.swagger.paths = {};
  var expandedParams = {};
  services.forEach((service) => {
    if (DEPRECATED.indexOf(service.$.name) !== -1) return;
    var actions = service.action;
    actions.forEach((action) => {
      var pathname = '/service/' + service.$.id + '/action/' + action.$.name;
      console.log('\n\n', pathname);
      var path = this.swagger.paths[pathname] = {};
      var log = DEBUG_OP.service === service.$.id && DEBUG_OP.action == action.$.name;
      let op = TARGET_API === 'ott'
          ? this.createPostOperation(service, action, path)
          : this.createGetOperation(service, action, path, expandedParams);
      op.responses = {
        '200': {
          description: 'Success',
        }
      }

      function getResponseSchema(type, arrayType) {
        if (type.indexOf('Kaltura') === 0) {
          return {'$ref': getRefFromClassname(type)};
        } else {
          let schema = {type: utils.convertType(result.$.type)};
          if (schema.type === 'file') schema.type = 'string'
          if (schema.type === 'array') {
            schema.items = getResponseSchema(arrayType);
          }
          return schema;
        }
      }
      var result = action.result[0];
      if (result) {
        op.responses['200'].schema = getResponseSchema(result.$.type, result.$.arrayType);
      }
      if (action.throws) {
        let errResp = op.responses['x-Errors'] = {description: ""};
        action.throws.filter(t => t.$).forEach(t => {
          let errName = t.$.name;
          if (errResp.description) errResp.description += '\n';
          errResp.description += '* `' + errName + '`';
          let details = errors.filter(e => e.$.name === errName)[0];
          if (details) errResp.description += ': ' + details.$.message;
        })
      }
    });
  });
}

const MAX_QUERY_PARAM_DEPTH = 4;

SwaggerBuilder.prototype.getExpandedQueryParameters = function(definitionName) {
  var getSubclasses = (defName) => {
    var subs = Object.keys(this.swagger.definitions).filter((label) => {
      var def = this.swagger.definitions[label];
      var inherits = (def.allOf || []).filter((i) => {
        return i.$ref === getRefFromClassname(defName);
      })
      return inherits.length;
    });

    var indirSubs = [];
    var addIndirectSubs = (s) => {
      var newSubs = getSubclasses(s).filter((name) => {
        return indirSubs.indexOf(name) === -1 && subs.indexOf(name) === -1;
      });
      indirSubs = indirSubs.concat(newSubs);
      newSubs.forEach(addIndirectSubs);
    }
    subs.forEach(addIndirectSubs);

    return subs.concat(indirSubs);
  }

  var getSuperclasses = (defName) => {
    var def = this.swagger.definitions[defName];
    var supers = (def.allOf || []).map(s => getClassnameFromRef(s.$ref));
    var superSupers = [];
    supers.forEach((s) => {
      var newSupers = getSuperclasses(s).filter(n => superSupers.indexOf(n) === -1);
      superSupers = superSupers.concat(newSupers);
    });
    return superSupers.concat(supers);
  }

  var params = [];
  var addParams = (defName, baseName, cond, skipSuper, skipSub) => {
    baseName = baseName || '';
    if (baseName.split(/\[/).length > MAX_QUERY_PARAM_DEPTH) return;
    var def = this.swagger.definitions[defName];
    if (!def) throw new Error("Definition " + defName + " not found")

    if (!skipSuper) {
      var superclasses = getSuperclasses(defName);
      superclasses.forEach((sc) => {
        addParams(sc, baseName, cond, true, true);
      })
    }

    var props = def.properties;
    for (var prop in props) {
      var propDef = props[prop];
      if (propDef.readOnly) continue;
      if (propDef.$ref) {
        var subDef = getClassnameFromRef(propDef.$ref);
        addParams(subDef, baseName + '[' + prop + ']', cond, false, false)
        return;
      }
      var items = undefined;
      if (propDef.items) {
        items = {anyOf: [propDef.items], type: 'object'};
        if (propDef.items.$ref) {
          var subDef = getClassnameFromRef(propDef.items.$ref);
          items.anyOf = items.anyOf.concat(getSubclasses(subDef).map(c => ({$ref: getRefFromClassname(c)})));
        }
      }
      var newParam = {
        type: propDef.type,
        items: items,
        in: 'query',
        name: baseName + '[' + prop + ']',
        enum: propDef.enum,
        'x-enumLabels': propDef['x-enumLabels'],
        'x-enumType': propDef['x-enumType'],
        description: propDef.description,
      };
      if (!newParam.enum && prop === 'orderBy') {
        let enumName = definitionName.replace('Filter', 'OrderBy');
        let enm = this.swagger['x-enums'][enumName];
        if (enm) {
          newParam.enum = enm.oneOf.map(v => v.enum[0]);
          if (!newParam.enum.length) delete newParam.enum;
          newParam['x-enumLabels'] = enm.oneOf.map(v => v.title);
          newParam['x-enumType'] = enumName;
        }
      }
      var oldParam = params.filter(p => p.name === newParam.name)[0];
      if (oldParam) {
        if (oldParam['x-showCondition']) {
          oldParam['x-showCondition'].value = oldParam['x-showCondition'].value.concat(cond.value);
          oldParam['x-showCondition'].value = _.uniq(oldParam['x-showCondition'].value);
        }
      } else {
        if (cond) newParam['x-showCondition'] = cond;
        params.push(newParam);
      }
    }

    if (!skipSub) {
      var subclasses = getSubclasses(defName);
      if (subclasses.length) {
        var paramName = baseName + '[objectType]';
        var existing = params.filter(p => p.name === paramName)[0];
        if (!existing) {
          params.push({
            name: paramName,
            in: 'query',
            enum: subclasses,
            type: 'string',
          });
        } else {
          subclasses = subclasses.filter(s => existing.enum.indexOf(s) === -1);
          existing.enum = _.uniq(existing.enum.concat(subclasses));
        }
        subclasses.forEach((subName) => {
          addParams(subName, baseName, {name: paramName, value: [subName]}, false, false);
        })
      }
    }
  }
  addParams(definitionName);
  return params;
}

SwaggerBuilder.prototype.fixDefinitions = function() {
  for (let def in this.swagger.definitions) {
    this.fixSchema(this.swagger.definitions[def]);
  }
}

SwaggerBuilder.prototype.fixSchema = function(schema) {
  console.log('fix', schema.type)
  if (schema.type === 'file') schema.type = 'string';
  if (schema.items) this.fixSchema(schema.items);
  if (schema.properties) {
    for (let key in schema.properties) {
      this.fixSchema(schema.properties[key])
    }
  }
}

SwaggerBuilder.prototype.fixFileOperations = function() {
  if (TARGET_API === 'ott') return;
  for (var path in this.swagger.paths) {
    var op = this.swagger.paths[path].get;
    var fileParams = op.parameters.filter(p => p.type === 'file');
    if (!fileParams.length) continue;
    fileParams.forEach(p => p.in = 'formData');
    this.swagger.paths[path].post = op;
    delete this.swagger.paths[path].get;
  }
}

SwaggerBuilder.prototype.setInputOptions = function() {
  const addDynEnum = (p, name, schema) => {
    var label = schema && 'name' in schema.properties ? 'name' : 'id';
    p['x-dynamicEnum'] = {
      path: '/service/' + name + '/action/list',
      method: 'get',
      array: 'objects',
      label: label,
      value: 'id',
    }
  }

  const adjustParameter = (p, schema, path) => {
    if (p.$ref) return;
    var isGet = path && path.match(/\/get$/);
    if (p.name === 'password') p['x-inputType'] = 'password';
    if (p.name.match(/Date\]?$/)) p['x-inputType'] = 'datetime';
    if (p.name === 'id' && isGet && schema) {
      addDynEnum(p, path.match(/service\/([^\/]*)\//)[1], schema);
      p['x-inputType'] = p.type === 'number' ? 'number' : 'text';
    }
    if (p.name === 'entryId' && isGet) {
      addDynEnum(p, 'media', {properties: {name: {type: 'string'}}});
      p['x-inputType'] = p.type === 'number' ? 'number' : 'text';
    }
    if (path === '/service/session/action/start' && p.name === 'expiry') {
      p.default = 86400;
    }
  }

  for (var path in this.swagger.paths) {
    var op = this.swagger.paths[path].get || this.swagger.paths[path].post;
    var schema = op.responses['200'].schema;
    if (schema) schema = this.resolveRef(schema);
    (op.parameters || []).forEach(p => adjustParameter(p, schema, path));
  }
  Object.keys(this.swagger.parameters || {}).map(k => this.swagger.parameters[k]).forEach(p => adjustParameter(p));
}

SwaggerBuilder.prototype.addErrors = function(errors) {
  this.swagger['x-errors'] = errors.map(err => {
    return err.$;
  })
}

SwaggerBuilder.prototype.resolveRef = function(schema) {
  var ref = schema.$ref;
  if (!ref) return schema;
  return this.swagger.definitions[getClassnameFromRef(ref)];
}
